### ISSUE TITLE
Missing function "components.m"

### ISSUE THREAD

**Issue by tangdale** [kunegis/konect-toolbox#2]
Dear Professor Kunegis,
         When I run konect_statistic_alcon(), it returns a error message "Undefined function or variable 'components'." I cannot find "components.m" in my MATLAB path or KONECT toolbox path. I am wondering whether could you tell me where can I find the m file? Thanks!
Best,
Chao

**Comment by kunegis** [comment]
Hello

You need to install the Boost Graph Library (BGL), which includes the function 'components'.  See the file 'README' in the KONECT Toolbox for installation instructions.  

Cheers
Jérôme

**Comment by mjpuma** [comment]
Hi Jérôme,

First, thanks for creating this.. and, more importantly, thanks in advance for your patience with my questions.

Is the BGL that you refer to here (http://www.boost.org/doc/libs/1_66_0/libs/graph/doc/index.html) or the Matlab specific one (http://dgleich.github.io/matlab-bgl/)?  I assume the latter.  

If so, could you provide some more guidance building on your README instructions?  I am unclear on the steps "install libstdc++5 " and "symlink the unzipped matlab_bgl to here".  I'm on a MacOS (10.11.6) and Matlab 2014a (although I have access to an updated matlab if that helps). 

Some specific questions:
- From the Terminal, where do I install ibstdc++5? (plus any help with the syntax would be a huge help...)
- What's the syntax for making the symlink and to where does "here" refer to?

The farthest I got was the error "Undefined function 'components_mex' for input arguments of type 'double'."  

Thanks!

Michael


Installation of BGL:
* Download version 4.0.1 from website (newer versions may not work)
* unzip it
* (on some systems:  install libstdc++5 from http://packages.debian.org/stable/base/libstdc++5)
* symlink the unzipped matlab_bgl to here

**Comment by kunegis** [comment]
Hello

I see you're using Macos :)  It should be possible to do that in principle, we we have never tried it.  You'll probably have to hack a few things -- maybe ask your local Unix guru  (We recommend GNU/Linux)

A few general comments:   In KONECT, we're following the "never change directories" principle -- everything will be executed from within the project's directory, in this case 'konect-analysis/'.  (That's what "here" refers to.)

> Is the BGL that you refer to here (http://www.boost.org/doc/libs/1_66_0/libs/graph/doc/index.html) or the Matlab specific one (http://dgleich.github.io/matlab-bgl/)? I assume the latter.

Correct, it's Matlab-BGL.  The instructions are in https://github.com/kunegis/konect-analysis/blob/master/lib/README

> install libstdc++5

Certain dependencies need an old version of the C++ standard library to be installed.  This is highly system-specific, so I guess using Macos you'll not have that particular problem (but probably others...)  Just go ahead and if libc++ is missing, you'll notice.

> symlink the unzipped matlab_bgl to here

It means that KONECT assumes that in the konect-analysis/ directory ("here"), there will be a directory named 'matlab_bgl' which is the Matlab-BGL directory.  The easiest is to create this as a symbolic link (link), using the 'ln -s' command.  I.e., if you have installed Matlab-BGL under ~/bin/matlab_bgl/, just go into the konect-analysis/ directory and execute "ln -s ~/bin/matlab_bgl/"; this will create the symlink.

(PS:  you can think of "ln -s" as a kind of "cheaply optimized cp command": just like 'cp A B' copies the file A to B, the command 'ln -s A B' symlinks the file A to B; hence the expression "symlink to".)

(Other side comment:  We follow the Unix nomenclature in which directories are a specific kind of file, so everything I wrote about "files" A/B etc. is also true for directories. Actual "arrays of bytes on the disk" are then called "regular files" under that nomenclature.)

> From the Terminal, where do I install ibstdc++5? (plus any help with the syntax would be a huge help...)

On Debian-based systems like Ubuntu it's using "apt install libstd++5".  On Macos I don't know; it may be via Brew.  Or maybe it's already installed by default.  Or you may get lucky by install clang, the C/C++ compiler of Macos.

> What's the syntax for making the symlink and to where does "here" refer to?

See above

Cheers & I hope that helps -- don't hesitate to ask further questions (I've amended konect-analysis/README to mention Matlab-BGL btw)

Jérôme

**Comment by kunegis** [comment]
One more comment:   As an alternative to symlinking matlab_bgl/, you can also directly add the full path to matlab_bgl/ to the Matlab path.

Questions:  
- Are you using only functions from konect-toolbox/, or do you also want to run things from konect-analysis/ ?
- Are you using GNU Octave or Matlab ?

**Comment by mjpuma** [comment]
Thanks very much for the quick response!  Also thanks for the link to matlab_bgl ( https://github.com/kunegis/konect-analysis/blob/master/lib/README).  I had missed that.

I am currently using Matlab along the proprietary nature of it is highly frustrating, so I am happy to see the Octave compatibility!  

At the moment, I am focused on the toolbox but, if I get things up and running, konect-analysis would be quite helpful as well.  I was previously using the Brain Connectivity Toolbox (https://sites.google.com/site/bctnet/), but it does not compute all of the network metrics that I need. (I'm focused on analyzing the global food trade network.)

I made the symbolic link and also added it to the matlab path, but I unfortunately still get the error "Undefined function 'components_mex' for input arguments of type 'double'." 

Do I have to compile the routines somehow?  And/or is this related to ibstdc++5?

**Comment by kunegis** [comment]
> Thanks very much for the quick response! Also thanks for the link to matlab_bgl ( https://github.com/kunegis/konect-analysis/blob/master/lib/README). I had missed that.
> 
Yep, I was confused myself between konect-analysis and konect-toolbox ; I work on konect-analysis much more often, but other people use konect-toolbox much more frequently :)

> I am currently using Matlab along the proprietary nature of it is highly frustrating, so I am happy to see the Octave compatibility!

Yes, although there are a few things that are not nice on Octave, such as the fact that the size of matrix is limited to signed 32 bit integers, so the 20 or so largest networks in KONECT cannot be analysed with it.  That's why I didn't continue to migrate things from Matlab to Octave.  (I also evaluated Julia to some extent.  I haven't tried Python in KONECT.)

>     
> At the moment, I am focused on the toolbox but, if I get things up and running, konect-analysis would be quite helpful as well. I was previously using the Brain Connectivity Toolbox (https://sites.google.com/site/bctnet/), but it does not compute all of the network metrics that I need. (I'm focused on analyzing the global food trade network.)
> 
> I made the symbolic link and also added it to the matlab path, but I unfortunately still get the error "Undefined function 'components_mex' for input arguments of type 'double'."
> 
> Do I have to compile the routines somehow? And/or is this related to ibstdc++5?

The _mex variant of a function means that it is compiled in C (or C++, Fortran, etc.), and is then called from Matlab.  This is Matlab-specific and I didn't get it to work woth Octave.  On Ubuntu, where I got it to work, I don't remember exactly the steps, but in principle this *should* be document by the Matlab-BGL distribution.

However, I was once starting to port some of the code to Octave, and came across the same problem (that the MEX functions of Matlab-BGL don't work, so I started to put in workaround, like here:

https://github.com/kunegis/konect-toolbox/blob/master/m/konect_connect_bipartite.m

Essentially, this is a workaround to avoid the dependency on Matlab-BGL altogether.  You may edit the file konect-toolbox/m/konect_usingoctave.m to always return 1.  

Btw, I think the only code that needs Matlab-BGL is the code needed to find the (largest) connected components, so depending on what statistics you want to compute, you may not need it.  But based on the fact that you hit that error, I guess you're doing something with the Laplacian matrix, or at least one of the normalized matrices :)

Cheers
Jérôme


https://github.com/kunegis/konect-toolbox/blob/master/m/konect_connect_bipartite.m
